// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbolbvnfndouxuwrufun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhib2xidm5mbmRvdXh1d3J1ZnVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTg3MDMsImV4cCI6MjA1OTYzNDcwM30.FHVxHsOSYPTusgrfzUGzIXXlcQ7baVgr8eksDgPgb6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);